/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentRequest } from '../../models/student-request';
import { StudentResponse } from '../../models/student-response';

export interface AddStudent$Params {

/**
 * ID de l'utilisateur à associer au profil étudiant
 */
  userId: number;
      body: StudentRequest
}

export function addStudent(http: HttpClient, rootUrl: string, params: AddStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
  const rb = new RequestBuilder(rootUrl, addStudent.PATH, 'post');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentResponse>;
    })
  );
}

addStudent.PATH = '/api/v1/students';
