/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentRequest } from '../../models/student-request';
import { StudentResponse } from '../../models/student-response';

export interface UpdateStudent$Params {
  id: number;
      body: StudentRequest
}

export function updateStudent(http: HttpClient, rootUrl: string, params: UpdateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
  const rb = new RequestBuilder(rootUrl, updateStudent.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentResponse>;
    })
  );
}

updateStudent.PATH = '/api/v1/students/{id}';
