/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationSummaryResponse } from '../models/application-summary-response';
import { TeacherSummaryResponse } from '../models/teacher-summary-response';
export interface AgreementResponse {
  application?: ApplicationSummaryResponse;
  creationDate?: string;
  documentPdfUrl?: string;
  endDate?: string;
  id?: number;
  startDate?: string;
  status?: 'DRAFT' | 'PENDING_VALIDATION' | 'VALIDATED' | 'SENT_FOR_SIGNATURE' | 'SIGNED' | 'CANCELED';
  validator?: TeacherSummaryResponse;
}
