/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeacherSummaryResponse } from '../models/teacher-summary-response';
export interface AgreementSummaryResponse {
  creationDate?: string;
  documentPdfUrl?: string;
  id?: number;
  status?: 'DRAFT' | 'PENDING_VALIDATION' | 'VALIDATED' | 'SENT_FOR_SIGNATURE' | 'SIGNED' | 'CANCELED';
  validator?: TeacherSummaryResponse;
}
