/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgreementRequest {
  documentPdfUrl?: string;
  endDate: string;
  startDate: string;
  status?: 'DRAFT' | 'PENDING_VALIDATION' | 'VALIDATED' | 'SENT_FOR_SIGNATURE' | 'SIGNED' | 'CANCELED';
  validatorId?: number;
}
