/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgreementSummaryResponse } from '../models/agreement-summary-response';
import { InternshipSummaryResponse } from '../models/internship-summary-response';
import { StudentSummaryResponse } from '../models/student-summary-response';
export interface ApplicationResponse {
  agreement?: AgreementSummaryResponse;
  applicationDate?: string;
  coverLetter?: string;
  cvUrl?: string;
  id?: number;
  internship?: InternshipSummaryResponse;
  status?: 'ACCEPTED' | 'REJECTED' | 'PENDING';
  student?: StudentSummaryResponse;
}
