/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InternshipSummaryResponse } from '../models/internship-summary-response';
import { StudentSummaryResponse } from '../models/student-summary-response';
export interface ApplicationSummaryResponse {
  applicationDate?: string;
  id?: number;
  internship?: InternshipSummaryResponse;
  status?: 'ACCEPTED' | 'REJECTED' | 'PENDING';
  student?: StudentSummaryResponse;
}
