/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummaryResponse } from '../models/user-summary-response';
export interface AuthResponse {
  accessToken?: string;
  refreshToken?: string;
  userSummaryResponse?: UserSummaryResponse;
}
