/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyRequest {
  address: string;
  description?: string;
  name: string;
  phone?: string;
  professionalEmail: string;
  website?: string;
}
