/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InternshipSummaryResponse } from '../models/internship-summary-response';
export interface CompanyResponse {
  address?: string;
  description?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  name?: string;
  phone?: string;
  professionalEmail?: string;
  publishedInternships?: Array<InternshipSummaryResponse>;
  telephone?: string;
  userId?: number;
  website?: string;
}
