/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanySummaryResponse } from '../models/company-summary-response';
export interface InternshipSummaryResponse {
  city?: string;
  company?: CompanySummaryResponse;
  country?: string;
  id?: number;
  title?: string;
}
