/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanySummaryResponse } from '../models/company-summary-response';
export interface InternshipResponse {
  city?: string;
  company?: CompanySummaryResponse;
  country?: string;
  description?: string;
  endDate?: string;
  id?: number;
  isActive?: boolean;
  isPaid?: boolean;
  startDate?: string;
  title?: string;
}
