/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InternshipRequest {
  city: string;
  country?: string;
  description: string;
  endDate: string;
  isActive?: boolean;
  isPaid?: boolean;
  startDate: string;
  title: string;
  validDates?: boolean;
}
