/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummaryResponse } from '../models/user-summary-response';
export interface MessageResponse {
  content?: string;
  id?: number;
  read?: boolean;
  recipient?: UserSummaryResponse;
  sender?: UserSummaryResponse;
  sentDate?: string;
}
