/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  id?: number;
  message?: string;
  notificationDate?: string;
  relatedUrl?: string;
  viewed?: boolean;
}
