/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentSummaryResponse {
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  level?: string;
}
