/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationSummaryResponse } from '../models/application-summary-response';
export interface StudentResponse {
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  level?: string;
  studentCode?: string;
  submittedApplications?: Array<ApplicationSummaryResponse>;
  telephone?: string;
  userId?: number;
}
