/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgreementSummaryResponse } from '../models/agreement-summary-response';
export interface TeacherResponse {
  department?: string;
  email?: string;
  firstName?: string;
  grade?: string;
  id?: number;
  lastName?: string;
  specialty?: string;
  telephone?: string;
  userId?: number;
  validatedAgreements?: Array<AgreementSummaryResponse>;
}
