/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeacherSummaryResponse {
  department?: string;
  email?: string;
  firstName?: string;
  grade?: string;
  id?: number;
  lastName?: string;
}
