/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  roles?: Array<'TEACHER' | 'STUDENT' | 'ADMIN' | 'COMPANY' | 'USER'>;
  telephone?: string;
}
