/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterRequest {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  roles: Array<string>;
  telephone?: string;
}
