/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponse } from '../../models/user-response';

export interface SearchUser$Params {

/**
 * Mot-clé de recherche globale
 */
  keyword?: string;

/**
 * Recherche exacte par email
 */
  email?: string;

/**
 * Recherche par nom
 */
  name?: string;
}

export function searchUser(http: HttpClient, rootUrl: string, params?: SearchUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, searchUser.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('email', params.email, {});
    rb.query('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

searchUser.PATH = '/api/v1/users/search';
