/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationResponse } from '../../models/notification-response';
import { NotificationUpdateRequest } from '../../models/notification-update-request';

export interface UpdateNotification$Params {
  id: number;
      body: NotificationUpdateRequest
}

export function updateNotification(http: HttpClient, rootUrl: string, params: UpdateNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, updateNotification.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationResponse>;
    })
  );
}

updateNotification.PATH = '/api/v1/notifications/{id}';
