/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationRequest } from '../../models/application-request';
import { ApplicationResponse } from '../../models/application-response';

export interface CreateApplicationWithCv$Params {
      body?: {
'application': ApplicationRequest;

/**
 * Fichier CV (PDF, DOCX)
 */
'cvFile': Blob;
}
}

export function createApplicationWithCv(http: HttpClient, rootUrl: string, params?: CreateApplicationWithCv$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, createApplicationWithCv.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationResponse>;
    })
  );
}

createApplicationWithCv.PATH = '/api/v1/applications/with-cv';
