/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationRequest } from '../../models/application-request';
import { ApplicationResponse } from '../../models/application-response';

export interface CreateApplicationForStudent$Params {

/**
 * ID de l'étudiant
 */
  id: number;
      body: ApplicationRequest
}

export function createApplicationForStudent(http: HttpClient, rootUrl: string, params: CreateApplicationForStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, createApplicationForStudent.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationResponse>;
    })
  );
}

createApplicationForStudent.PATH = '/api/v1/applications/for-student/{id}';
