/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationResponse } from '../../models/application-response';

export interface GetApplicationById$Params {

/**
 * Identifiant de la candidature
 */
  id: number;
}

export function getApplicationById(http: HttpClient, rootUrl: string, params: GetApplicationById$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResponse>> {
  const rb = new RequestBuilder(rootUrl, getApplicationById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationResponse>;
    })
  );
}

getApplicationById.PATH = '/api/v1/applications/{id}';
