/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AgreementRequest } from './models/agreement-request';
export type { AgreementResponse } from './models/agreement-response';
export type { AgreementSummaryResponse } from './models/agreement-summary-response';
export type { ApplicationRequest } from './models/application-request';
export type { ApplicationResponse } from './models/application-response';
export type { ApplicationSummaryResponse } from './models/application-summary-response';
export type { AuthResponse } from './models/auth-response';
export type { CompanyRequest } from './models/company-request';
export type { CompanyResponse } from './models/company-response';
export type { CompanySummaryResponse } from './models/company-summary-response';
export type { InternshipRequest } from './models/internship-request';
export type { InternshipResponse } from './models/internship-response';
export type { InternshipSummaryResponse } from './models/internship-summary-response';
export type { MessageRequest } from './models/message-request';
export type { MessageResponse } from './models/message-response';
export type { NotificationResponse } from './models/notification-response';
export type { NotificationUpdateRequest } from './models/notification-update-request';
export type { PageableObject } from './models/pageable-object';
export type { PageMessageResponse } from './models/page-message-response';
export type { Resource } from './models/resource';
export type { SortObject } from './models/sort-object';
export type { StudentRequest } from './models/student-request';
export type { StudentResponse } from './models/student-response';
export type { StudentSummaryResponse } from './models/student-summary-response';
export type { TeacherRequest } from './models/teacher-request';
export type { TeacherResponse } from './models/teacher-response';
export type { TeacherSummaryResponse } from './models/teacher-summary-response';
export type { UserLoginRequest } from './models/user-login-request';
export type { UserRegisterRequest } from './models/user-register-request';
export type { UserResponse } from './models/user-response';
export type { UserSummaryResponse } from './models/user-summary-response';
