/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgreementRequest } from '../../models/agreement-request';
import { AgreementResponse } from '../../models/agreement-response';

export interface CreateAgreementForAdmin$Params {

/**
 * ID de la candidature
 */
  applicationId: number;

/**
 * ID de l'enseignant
 */
  teacherId: number;
      body: AgreementRequest
}

export function createAgreementForAdmin(http: HttpClient, rootUrl: string, params: CreateAgreementForAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<AgreementResponse>> {
  const rb = new RequestBuilder(rootUrl, createAgreementForAdmin.PATH, 'post');
  if (params) {
    rb.query('applicationId', params.applicationId, {});
    rb.query('teacherId', params.teacherId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgreementResponse>;
    })
  );
}

createAgreementForAdmin.PATH = '/api/v1/agreements/admin-create';
