/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgreementResponse } from '../../models/agreement-response';

export interface GetAllAgreements$Params {
}

export function getAllAgreements(http: HttpClient, rootUrl: string, params?: GetAllAgreements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AgreementResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllAgreements.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AgreementResponse>>;
    })
  );
}

getAllAgreements.PATH = '/api/v1/agreements';
