/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgreementRequest } from '../../models/agreement-request';
import { AgreementResponse } from '../../models/agreement-response';

export interface UpdateAgreement$Params {
  id: number;
      body: AgreementRequest
}

export function updateAgreement(http: HttpClient, rootUrl: string, params: UpdateAgreement$Params, context?: HttpContext): Observable<StrictHttpResponse<AgreementResponse>> {
  const rb = new RequestBuilder(rootUrl, updateAgreement.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgreementResponse>;
    })
  );
}

updateAgreement.PATH = '/api/v1/agreements/{id}';
