/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgreementResponse } from '../../models/agreement-response';

export interface ValidateAgreement$Params {
  id: number;
}

export function validateAgreement(http: HttpClient, rootUrl: string, params: ValidateAgreement$Params, context?: HttpContext): Observable<StrictHttpResponse<AgreementResponse>> {
  const rb = new RequestBuilder(rootUrl, validateAgreement.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgreementResponse>;
    })
  );
}

validateAgreement.PATH = '/api/v1/agreements/{id}/validate';
