/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InternshipRequest } from '../../models/internship-request';
import { InternshipResponse } from '../../models/internship-response';

export interface CreateInternship$Params {
      body: InternshipRequest
}

export function createInternship(http: HttpClient, rootUrl: string, params: CreateInternship$Params, context?: HttpContext): Observable<StrictHttpResponse<InternshipResponse>> {
  const rb = new RequestBuilder(rootUrl, createInternship.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InternshipResponse>;
    })
  );
}

createInternship.PATH = '/api/v1/internships';
