/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Resource } from '../../models/resource';

export interface DownloadCv$Params {

/**
 * Nom complet du fichier avec son extension (ex: cv_jean.pdf)
 */
  filename: string;
}

export function downloadCv(http: HttpClient, rootUrl: string, params: DownloadCv$Params, context?: HttpContext): Observable<StrictHttpResponse<Resource>> {
  const rb = new RequestBuilder(rootUrl, downloadCv.PATH, 'get');
  if (params) {
    rb.path('filename', params.filename, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Resource>;
    })
  );
}

downloadCv.PATH = '/api/v1/files/cv/{filename}';
