/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyRequest } from '../../models/company-request';
import { CompanyResponse } from '../../models/company-response';

export interface CreateCompany$Params {

/**
 * ID de l'utilisateur rattaché à l'entreprise
 */
  userId: number;
      body: CompanyRequest
}

export function createCompany(http: HttpClient, rootUrl: string, params: CreateCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyResponse>> {
  const rb = new RequestBuilder(rootUrl, createCompany.PATH, 'post');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyResponse>;
    })
  );
}

createCompany.PATH = '/api/v1/companies';
