/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyResponse } from '../../models/company-response';

export interface GetCompanyById$Params {

/**
 * Identifiant unique de l'entreprise
 */
  id: number;
}

export function getCompanyById(http: HttpClient, rootUrl: string, params: GetCompanyById$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyResponse>> {
  const rb = new RequestBuilder(rootUrl, getCompanyById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyResponse>;
    })
  );
}

getCompanyById.PATH = '/api/v1/companies/{id}';
